version: '3'

services:
  redis1:
    image: redis:latest
    ports:
      - "7000:6379"
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis_data:/data

  redis2:
    image: redis:latest
    ports:
      - "7001:6379"
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis_data:/data

  redis3:
    image: redis:latest
    ports:
      - "7002:6379"
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis_data:/data


  redis-trib:
    image: redis:latest
    command: redis-cli --cluster create redis1:6379 redis2:6379 redis3:6379 --cluster-replicas 1
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
